// app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Nav from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

import "./globals.css";

// 🌟 Import the CampaignsProvider from the specified path
import { CampaignsProvider } from "@/context/CampaignsContext"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap all interactive content with the Provider */}
        <CampaignsProvider> 
          <Nav />
          <main className="">{children}</main>
          <Footer />
        </CampaignsProvider>
      </body>
    </html>
  );
}